steps:
# Build the latest version.
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'package']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', './microservice-kubernetes-demo/docker-build.sh']
  
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', './microservice-kubernetes-demo/microservices.yaml']
  env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-a', 'CLOUDSDK_CONTAINER_CLUSTER=micro-cluster']
  
# Add more power, and more time, for build
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'
